<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="BenchmarkDotNet.Annotations" Version="0.15.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\guard\SGuard.csproj" />
    </ItemGroup>

</Project>
